[mgr]
hovered = { fg = "#430088", bg = "#d7baff" }
border_style = { fg = "black" }

# Mode are bottom left - right side
[mode]
normal_main = { bg = "#8a55d7", fg = "#fef6ff" }
normal_alt = { bg = "#513d6f", fg = "#c3abe4" }

# Status bar
[status]
overall = { bg = "#1e1a22", fg = "#e8e0eb" }

[filetype]
rules = [
# fallback - Dir
    { name = "*/", fg = "#d5bcf7" }
]
